server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://120.24.27.141:3306/undercover_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=CTT
    username: root
    password: hhq123
    type: com.zaxxer.hikari.HikariDataSource

  flyway:
    enabled: false
    locations: classpath:/db

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


wx:
  miniapp:
    configs:
      - appid: wxf0eaa400e8368722
        secret: 813846576a28b49863bbae2dd7d27113
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
