spring:
  datasource:
    url: jdbc:mysql://120.24.27.141:3306/undercover_dev?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=CTT
    username: root
    password: hhq123
    type: com.zaxxer.hikari.HikariDataSource

  flyway:
    enabled: false
    locations: classpath:/db

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8888
